services:
  db:
   image: postgres:16-alpine
   environment:
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
    - ./docker/postgres_data:/var/lib/typeorm/data:z

  db_test:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres_data_test:/var/lib/postgresql/data:z

volumes:
  postgres_data:
  postgres_data_test:



