name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Conectar à instância EC2 e rodar o deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd /home/ec2-user/ANOUT24_D02_COMPASSCAR_PRIME_NODE || exit
            git pull origin main || exit
            rafael-arashiro || exit
            ${{ secrets.GIT_TOKEN }}|| exit
            npm install || exit
            npm run build || exit
            pm2 restart node-api-compasscar || pm2 start dist/main.js --name "node-api-compasscar"
          EOF
