name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - run: npm ci
      - run: npm run build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /ANOUT24_D02_COMPASSCAR_PRIME_NODE
          remote_host: <host>.compute.amazonaws.com
          remote_user: ec2-user
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
